<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assigned At' => '分配时间',
    'Add Txt' => '补录文字',
    'Block Num' => '栏号',
    'Welcome to {name}, please activate your account' => '欢迎您来到{name}，请激活您的帐号',
    'This email has already been taken.' => '',
    'Your account has been successfully activated.' => '您的账号已经激活。随喜您报名智能信息中心义工。请您耐心等待，两周之内会有人力资源义工联系您面试。',
    'Your account has been successfully created. Check your email for further instructions.' => '您的账号已建立，请检查您的注册邮箱新邮件以获得进一步说明。',
    'Your activation link: {url}' => '请激活您的帐号：{url}',
    'About' => '关于',
    'Account Settings' => '帐号设置',
    'Articles' => '文章',
    'Attachments' => '附件',
    'Backend' => '后台',
    'Body' => '内容',
    'Check your email for further instructions.' => '请检查您的邮件',
    'Check Txt' => '校对结果',
    'Completed At' => '完成时间',
    'Confirm Password' => '密码确认',
    'Confirm Txt' => '审查结果',
    'Contact' => '联系',
    'Create' => '创建',
    'Created At' => '创建时间',
    'E-mail' => 'Email',
    'Email' => 'Email',
    'Error Char' => '阙疑文字',
    'Error while oauth process.' => 'oauth进程错误',
    'Female' => '女性',
    'Home' => '主页',
    'Help' => '帮助',
    '<a href="{link}">If you forgot your password you can reset it here</a>' => '<a href="{link}">如忘记密码请点此重置 </a>',
    'Line Num' => '行号',
    'Line Txt' => '行文本',
    'If Doubt' => '是否存疑',
    'If Match' => '图文是否匹配',
    'Image Path' => '图片路径',
    'Incorrect username or password.' => '用户名或密码错误',
    'Is Right' => '是否正确',
    'Language' => '语言',
    'Log in with' => 'Log in with',
    'Login' => '登录',
    'Logout' => '退出',
    'Male' => '男性',
    'Name' => '名字',
    'Need an account? Sign up.' => '需要一个帐号？请注册',
    'New password was saved.' => '新密码保存成功',
    'Page Code' => '页码',
    'Page not found' => '页面没找到',
    'Page Source' => '图片来源',
    'Page Type' => '图片类型',
    'Page Origin Type' => '图片初始类型',
    'Password' => '密码',
    'Password reset for {name}' => '为{name}重置密码',
    'Profile settings' => '资料设置',
    'Remark' => '备注',
    'Remember Me' => '记住我',
    'Request password reset' => '请求重置密码',
    'Reset password' => '重置密码',
    'Settings' => '设置',
    'Sign up with' => '注册',
    'Signup' => '注册',
    'Sorry, we are unable to reset password for email provided.' => '根据您提供的Email无法充值密码',
    'Status' => '状态',
    'Subject' => '主题',
    'Submit' => '提交',
    'Task Type' => '任务类型',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '感谢你您联系我们，我们会尽快回复',
    'There was an error sending email.' => '发送邮件时发生错误',
    'This email address has already been taken.' => '此邮件已被占用',
    'This username has already been taken.' => '用户名已经被占用',
    'Tptk Add Thou Chars' => '千字文补录',
    'Tptk Error Chars' => '阙疑文字',
    'Tptk Error Char ID' => '阙疑文字ID',
    'Tptk Pages' => '图文类型检查',
    'Update' => '更新',
    'User Settings' => '用户设置',
    'User ID' => '用户ID',
    'Username' => '用户名',
    'Username or email' => '用户名或Email',
    'Verification Code' => '验证码',
    'We already have a user with email {email}' => '我们已经有用户使用了该邮箱',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '欢迎来到{app-name}. 您的登录信息我们已经发送到了您的注册邮箱.',
    'Your account has been successfully saved' => '您的帐号保存成功',
    '{app-name} | Your login information' => '{app-name} | 您的登录信息',
    'Send' => '发送',
];
